// library
export const ACTION_TYPE = {
    ADD_BOOKS: "ADD_BOOKS",
    DELETE_BOOK: "DELETE_BOOK",
    DELETE_ALL_BOOKS: "DELETE_ALL_BOOKS",
};

//fetch
export const FETCH_ACTION_TYPE = {
    BOOKS_IS_LOADING: "BOOKS_IS_LOADING",
    BOOKS_LOADING_SUCCESS: "BOOKS_LOADING_SUCCESS",
    BOOKS_LOADING_ERROR: "BOOKS_LOADING_ERROR",
};
